version: "3.9"

services:
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: >
      redis-server --appendonly yes --requirepass root

    volumes:
      - redis-data:/data
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"

volumes:
  redis-data:
